name: Notify Google Chat on Action Run

on:
  push:
  pull_request:
  workflow_run:
    workflows: ["CodeQL"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Google Chat
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "text": "🚀 GitHub Action executed in *Mervin-Abraham/FileSync* \n
                         *Event:* ${{ github.event_name }} \n
                         *Status:* ${{ job.status }} \n
                         *Commit:* `${{ github.sha }}` \n
                         *Triggered by:* ${{ github.actor }} \n
                         *Run details:* [View Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
              }' \
          "${{secrets.GOOGLE_CHAT_WEBHOOK_URL }}"
